name: ml-ids-gradient-boost-catboost
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - h5py
  - pandas
  - catboost
  - imbalanced-learn
  - scikit-learn
  - scipy
  - click
  - cloudpickle
  - pip:
    - tables
    - keras
    - mlflow