name: ml-ids
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - catboost
  - click
  - cloudpickle
  - imbalanced-learn
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - pylint
  - pytest
  - pytest-runner
  - python
  - python-dateutil
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - h5py
  - pip:
    - mlflow
    - sagemaker
    - h5py
    - hyperopt
    - keras
    - keras-applications
    - keras-preprocessing
    - tables
    - tensorflow-estimator
